[book]
authors = ["sunface"]
language = "zh-CN"
title = "Beat AI"
src = "src"

[output.html]
no-section-label = true
additional-css = ["theme/style1.css"]
additional-js = ["assets/custom1.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/sunface/BeatAI"
edit-url-template = "https://github.com/sunface/BeatAI/edit/main/{path}"

[output.html.playground]
editable = true
copy-js = true
# line-numbers = true

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2021" #在线运行用2021版本的
